### ISSUE TITLE
Access to the dataset

### ISSUE THREAD

**Issue by OrientedDeer** [snappdragonn/CritRoleHpTracker#2]
Hello!

I'm an undergraduate student interested in making my capstone project based on something similar to this. Is there any chance I could get access or a zip file for your dataset?

I want to try and make a NLP model that reads the transcripts and uses it to track the damage dealt. While I could try and annotate the transcripts myself but I wanted to reach out first and see if your dataset would solve that for me.

Thanks
Charles

**Comment by snappdragonn** [comment]
Sure, here's the data
[data.zip](https://github.com/snappdragonn/CritRoleHpTracker/files/10471905/data.zip)

Good luck with the NLP model, I hope this helps :)
