### ISSUE TITLE
Extension suddenly isn't working at all

### ISSUE THREAD

**Issue by Morgan-Rewis** [snappdragonn/CritRoleHpTracker#3]
So I fell about 8 episodes behind on C3, and when I went back to try and catch up the popup suddenly isn't appearing, even after refreshing the page and uninstalling/reinstalling it (even though I know it was working on this episode before)

In Chrome's "Manage Extensions" page, this error has appeared:
![image](https://github.com/snappdragonn/CritRoleHpTracker/assets/29361536/7b952910-f732-4fd7-96f6-6ae0f735e988)

It seems like maybe YouTube changed something about how you get the channel name? That's just my guess, I know nothing about JavaScript or making extensions

**Comment by ChusSay** [comment]
Hey! Been having the same problem on YouTube, It works fine on Twitch though.

**Comment by snappdragonn** [comment]
Yep I'm working on this. 
You're right YouTube seems to have updated and the html element I was using to get the channel name no longer exists.

**Comment by snappdragonn** [comment]
A bit late sorry but if you haven't already seen this should be fixed for now (at least until YouTube changes it again). I'll try working on a more permanent solution but I'm not sure what that will be yet as I can't see any way to get the channel name other than finding it somewhere in the DOM.
