### ISSUE TITLE
Typos in Keg's Int score (C2E26)

### ISSUE THREAD

**Issue by pcordes** [snappdragonn/CritRoleHpTracker#6]
Her int is 9, not 19.  (stat card https://youtu.be/NZVqPja6Alg?si=eqig2lDf4ZTyAZiH&t=3265 )

You have her other stats correct, including AC 19, perhaps a typo.  Also Con 18 is correct.  The on-stream stat card incorrectly shows Con 12 in this episode, and C2E27, C2E28.  I don't see a stat card in the C2E29 live show.  Or in C2E30 (Ashly wasn't there, and Keg just left a note.)

18 Con would make her rolled HP 6 per d10 hit die, exactly what she'd get from taking the average instead of rolling.   
 `(54 - 10 - 5*4) / 4` = 6
12 Con would require near-perfect rolls on the fighter d10 hit dice.   
`(54 - 10 - 5*4) / 4` = 9.75

So I don't know where the Con 18 actually comes from, but I think it's correct based on her HP.

Critrolestats (https://www.critrolestats.com/pcstats-wm ) has a stat card with Con 18, in an art style that looks like the live-show 
https://criticalrole.miraheze.org/wiki/Keg and https://criticalrole.fandom.com/wiki/Keg both show her Con as 18, but cite her C2E26 stat card as a reference (which shows Con 12).

---

I also noticed while checking that the stat tracker for C2E30 is showing Beau's max HP as 6.  That's her level.
The stat card at 17:39 shows her at 38/54 HP.  That's her level 6 total, despite the stat card that episode showing some party members still at level 5.  They do milestone leveling so we know that's just a typo in the stream graphics.  (Errors in stat cards are not rare; Imogen's Dex has been wrong for months.)

**Comment by snappdragonn** [comment]
Thanks, fixed Kegs int and Beaus hp.
