### ISSUE TITLE
Caleb's Int too high at level 3

### ISSUE THREAD

**Issue by pcordes** [snappdragonn/CritRoleHpTracker#8]
Rewatching a bit of episode 7 while they were still level 3, the mouseover showed Caleb's Int score as 20.
The stat card shows it as 18 for that episode, only going up to 20 at level 4 (episode 13).

I looked at Caleb's stats because Liam said Caleb needed more Intelligence after missing with a Fire Bolt, which also wouldn't make sense if his Int was already 20.  (He's already doing well as a human to have Int 18 before the first ASI.)

Stats for Jester are correct for level 3, Wis and Dex 17.  I didn't check other characters.

**Comment by snappdragonn** [comment]
Thanks, it should be fixed now. I checked the other characters stats and I think they all look correct.
