### ISSUE TITLE
Fearne should have two lvl5 spell slots from multiclassing Arcane Trickster

### ISSUE THREAD

**Issue by pcordes** [snappdragonn/CritRoleHpTracker#9]
After the level-up to 12th, Arcane Trickster 3 + Druid 9 has the spell slots of a 10th-level caster.
(She gained Disguise Self from that level-up, which pretty much confirms Arcane Trickster.  Interestingly there's no Int requirement to multiclass into rogue, even if you choose Arcane Trickster.)

https://fexlabs.com/5eslots/

**Comment by snappdragonn** [comment]
Thank you, there's no way I would have worked that out myself.
I've updated it now.
